### ISSUE TITLE
[REQ] Spring Boot 3 support and file generation with javax imports in oauth1-signer-java

### ISSUE THREAD

**Issue by Fran313** [Mastercard/oauth1-signer-java#42]
I'm working on a project that uses Mastercard's oauth1-signer-java, and I've encountered an issue related to Spring Boot 3 support and generating files with imports from javax instead of jakarta.

When trying to compile my project with Spring Boot 3, I encounter a series of errors in the logs indicating that the Generated symbol cannot be found in the javax.annotation package. I attach some examples of the errors I am seeing in the logs:

[ERROR]   symbol:   class Generated
[ERROR]   location: package javax.annotation
[ERROR] /route/to/my/proyect/target/generated-sources/openapi/src/gen/java/com/mastercard/api/mastercom/model/TransactionSummary.java:[53,17] error: cannot find symbol

I've done some research and it looks like these errors may be related to incompatibility between Spring Boot 3 and the oauth1-signer-java dependency. I'm wondering if there are any plans to address this incompatibility in future versions of the project.

Any help or suggestions to resolve this issue would be greatly appreciated.

Additional Context:

- Using Spring Boot 3.0.9
- oauth1-signer-java version 1.5.3
- Java 17

**Comment by NehaSony** [comment]
Hi @Fran313 

Thanks for reporting this issue. We will look into this issue and get back to you.

**Comment by NehaSony** [comment]
Hi @Fran313 

Looks like when upgrading an existing application to Spring Boot 3.0.9 with Java 17 we see javax.annotation-api dependency missing. If you look into the source of the error shared :

```
[ERROR] /route/to/my/proyect/target/generated-sources/**openapi**/src/gen/java/com/mastercard/api/mastercom/model/TransactionSummary.java:[53,17] error: cannot find symbol
```
The origin of these errors are the missing imports for @Generated annotation.  This [issue](https://github.com/OpenAPITools/openapi-generator/issues/14010 ) is found and fixed in the later version of openapi generator.

The recommended solution would be to use the latest version of openapi-generator or version 7+

**Comment by Fran313** [comment]
Hi @NehaSony 

I appreciate your prompt response. That solved my problem.
